---
# Slurm config (optional)
name: "SLURM"   # MUST BE "SLURM"

# Required
partition: "single"
job-name: "slurm_test"    # this will be the experiment's name in slurm


# Required - Cluster Specific
num_parallel_jobs: 1
ntasks: 1 # for single partition
cpus-per-task: 1
mem-per-cpu: 750
time: 10  #in  

---
name: "bbrl_airhockey"

# Required: Can also be set in DEFAULT
path: './results'
iterations: 10
repetitions: 1 # number of times one set of parameters is run
reps_per_job: 1
reps_in_parallel: 1 # need to be 1 in order for wandb to work properly

params:
  exp_name: "bbrl_airhockey"
  env_id: "fancy_ProDMP/AirHockey-3dof-hit-airhockit2023-v0"
  # env_id: "fancy_ProDMP/AirHockey-7dof-hit-airhockit2023-v0"
  n_envs: 4
  n_envs_test: 4
  n_eval_samples: 75

  norm_advantages: 1
  clip_advantages: 0.0
  norm_buffer_size: 10

  proj_type: "kl"
  mean_bound: 0.05
  cov_bound: 0.0005
  entropy_eq: 0
  entropy_first: 0
  scale_prec: 1
  target_entropy: 0.0
  temperature: 0.5
  entropy_schedule: 0
  trust_region_coeff: 25.0

  optimizer_policy: "adam"
  optimizer_critic: "adam"
  lr_critic: 0.0003
  lr_schedule: false
  lr_policy: 0.0003
  epochs: 100

  val_epochs: 100

  num_minibatches: 1
  entropy_penalty_coeff: 0.0

  importance_ratio_clip: 0.0
  clip_vf: 0.0
  clip_grad_norm: 0.0

  initialization: "orthogonal"
  activation: "tanh"
  policy_type: "diag"
  scaled_std: 0
  minimal_std: 0.00001
  init_std: 1.0
  init_mean: 0.0
  contextual_std: 0
  contextual: 1
  hidden_sizes_policy: [ 32, 32 ]
  use_critic: 0
  hidden_sizes_critic: [ 32, 32 ]

  do_regression: 0
  regression_iters: 5
  lr_reg: 0.0001
  optimizer_reg: "adam"

  cpu: 1
  verbose: 1
  log_interval: 1
  save_interval: 1
  dtype: "float64"
grid:
    n_samples: [320]
    hidden_sizes_policy: [[32,32]]
    mean_bound: [0.05]
    cov_bound: [0.001]
    lr_policy: [0.0003]
    use_critic: [0]
    policy_type: ['full']
wandb:
    project: airhockit
    entity: airhockey_praktikum_23_24
    group: bbrl
